# Swedish notes

| | | | | | |
|-|-|-|-|-|-|
| | | | | | |

## Bostäder

**Hur bor du i Stockholm?**
Jag bor inte i Stockholm, men i Norrtälje i ett studentrum. Jag har en rumskompis som heter Laia. Hon är spanska.

**Hur bodde du i ditt hemland?**
För två år sedan, bodde jag med mina föräldrar och mina systrar i Paris men förra året, bodde jag i ett studentrum i Lyon.
Jag hade inte en rumskompis.

**Är det dyrt eller billigt att bo i Stockholm?**
Det är dyrt att bo i Stockholm men det är dyrare att bo i Paris i en lägenhet, inte med sina föräldrar.
Jag tror det är så dyrt att bo i Lyon i ett studentrum men en lägenhet är billigare. 

**Är det lätt eller svårt att hitta en bostad i Stockholm?**
Jag tror det är svårt att hitta en bostad i Stockholm men jag hade inte detta problem eftersom jag hade en bostad med KTH.

| | | | | | |
|-|-|-|-|-|-|
| jag söker |  je cherche | jag hittar | je trouve | 

## Framtidsplaner 1

**Vad ska du studera?**
- Jag _studerar_ IT och datavetenskap på KTH Kista. Jag _pluggar_ till civilinjeniör i IT. Jag studerar också vetenskapfilosophi.
- Ar det intressant ?

**Vad vill du göra på fritiden?**
- Jag _brukar_ träffa vänner.
- Jag går _alltid/ofta/sällan/aldrig_ på bio.
- Jg gå på krogen _ibland_.
- Vad gör du på _fredagar/lördagar_ ?
- Brukar ni gitta på teve ?

**Planerar du att resa någonstans?** _Planning a trip somewhere?_
- Jag planera att resa i Sverige, jag vill åker i Göteborg.
- Jag resade till Riga förra veckan, det vad bra !
- Ska du åka buss eller flygplan ?

**Kommer någon och besöker dig?**
- Jag, mina foraldrar besökde mig förra månaden.
- Vi promenerade i Stockholm och gick på Modernmuseet.
- Vad gjorde ni ?


## Framtidsplaner 2

### Question / Answers

**Var ska du arbeta?**
Jag tror att jag ska arbeta i Paris för att vara stängd från min familj men jag vill resa så jag skulle vilja arbeta i New York eller London.

**Planerar du att resa någonstans?**
Förra helgen, resade jag i Riga i Lettland med mina kompisar. Vi resade på en färja. Vi vill resa till Lappland i februari.

**Kommer du att besöka Stockholm/Sverige igen?**
Jag tror att jag  ska ofta gå till Stockholm igen eftersom min pojkvän bor i Kista.
Jag älskar Stockholm och jag vill besöka Göteborg och Uppsala.

## En drömresa

**Vart vill du helst resa?** _Where would you rather go?_
- Jag helst resa till USA
- Varfor vill du resa till... ?
- Eftersom jag tror att USA är mycket intressant, det finns vackra (_beautiful_) städer som New York

**Vad vill du göra där (vila, shoppa, gå på museum…)?**
- Om jag resa till New York, jag vill gå på modernmuseet och promenera i Central Park.

**Hur åker man dit?**
- Jag ska åker flygplan från Paris
- Är det dyrt eller billigt ?

**När är en bra tid att resa dit?** _When is a good time to travel there?_
- Jag tror att sommar är en bra tid att resa till New York.

## Drömjobb

**Vilket yrke vill du helst ha?**
- Jag helst jobbar på en stor företag, som Microsoft eller Facebook
- Jag kan arbeta mycket om jag är intresserad av arbetet
- Vill ni arbetar i ert hemland eller i annat land ?

**Varför är det ett bra yrke?**
- Arbetet är bra eftersom man kan jobba med intressant personer
- Jag ska har mycket pergar

**Vad är viktigt när man väljer yrke (intresse, lön, status, arbetstider)?** _What is important when choosing a profession (interest, salary, status, working hours)?_
- Jag tror att intresse är _viktigast_, eftersom man kan arbeta mycket om man är inresserad. 
- Arbetstider är viktig om man har barn.

**Kan du tänka din att flytta/flytta utomlands för att få ett bra jobb?**
- Absolut.
- Jag tror att flytta utomlands är bra _när_ man är ung
- Man kan träffas mycket personer
- Ska du flytta längt från ditt hemland ?



## Maten i Sverige och era hemländer

**Vilka svenska maträtter har du testat? Vad tyckte du?**
Jag har testat köttbullar och kanelbullar. Jag tror att köttbullar är gott men jag gillade inte kanelbullar.

**Vad är lika/olika i Sverige och i era hemländer?**
I Frankrike, äter vi ofta bröd med choklad eller croissant men i Sverige, dom äter kanelbullar.

**Vilken mat är dyr/billig i Sverige/era hemländer?**
Allt är dyrare i Sverige med undantag för fisk. Kaffe är mycket billigare i Frankrike än i Sverige.

**Finns det någon mat/maträtt som du kommer att sakna när du kommer tillbaka till ditt hemland?**
Jag gillar Ballerina kaka och jag kommer att sakna det i Frankrike.

## Fritidsaktiviteter

**Gör du lika/olika saker i Sverige och i ditt hemland?**
Jag ser alltid folk jogga i Norrtälje och det är bra. Jag skulle vilja jogga men jag gillar inte sport.
Det finns många sjöar i Sverige och det är bra att promenera.

**Vad tycker du bäst om att göra i Sverige?**
Jag tycker om att gå i skogen och att vara med mina vänner i en bar i Stockholm dricka en öl.

**Saknar du något som du brukar göra i ditt hemland?**
Jag saknar dansklasser i Sverige eftersom det är för dyrt här.

**Kommer du att sakna något som du har gjort i Sverige när du kommer tillbaka till ditt hemland?**
Jag kommer att sakna att resa lätt med färjor.

## Vädret i Sverige

**Hur kan man beskriva vädret i Sverige?**
Vädret är mycket värre i Sverige än i Frankrike. Det har varit kall i två månader och det ofta regnar.


**Vad är lika/olika i Sverige och i ditt hemland?**
I Sverige, är vädret dåligt från oktober till april och i Frankrike, är vädret dåligt från slutet av november till mars.


**Vad tycker du om det svenska vädret?**


**Vilket väder vill du ha för att du ska må bra?**


**Påverkar vädret i Sverige livsstilen?**



