# Swedish notes

|  |  |  |  |  |  |
| ------------- | ------------- | ------------- | ------------- |------------- |------------- |
| Row 1 Cell 1  | Row 1 Cell 2  | Row 1 Cell 2  | Row 1 Cell 2  | Row 1 Cell 2  | Row 1 Cell 2  |
| Row 1 Cell 1  | Row 1 Cell 2  | Row 1 Cell 2  | Row 1 Cell 2  | Row 1 Cell 2  | Row 1 Cell 2  |

## Framtidsplaner 1

### Questions / Answers

**Vad ska du studera?**
- Jag _studerar_ IT och datavetenskap på KTH Kista. Jag _pluggar_ till civilinjeniör i IT. Jag studerar också vetenskapfilosophi.
- Ar det intressant ?
**Vad vill du göra på fritiden?**
- Jag _brukar_ träffa vänner.
- Jag går _alltid/ofta/sällan/aldrig_ på bio.
- Jg gå på krogen _ibland_.
- Vad gör du på _fredagar/lördagar_ ?
- Brukar ni gitta på teve ?
**Planerar du att resa någonstans?** _Planning a trip somewhere?_
- Jag planera att resa i Sverige, jag vill åker i Göteborg.
- Jag resade till Riga förra veckan, det vad bra !
- Ska du åka buss eller flygplan ?
**Kommer någon och besöker dig?**


