# Swedish notes

| | | | | | |
|-|-|-|-|-|-|
| | | | | | |

## Bostäder

### Questions/Answers

**•	Hur bor du i Stockholm?**
Jag bor inte i Stockholm, men i Norrtälje i ett studentrum. Jag har en rumskompis som heter Laia. Hon är spanska.

**•	Hur bodde du i ditt hemland?**
För två år sedan, bodde jag med mina föräldrar och mina systrar i Paris men förra året, bodde jag i ett studentrum i Lyon.
Jag hade inte en rumskompis.

**•	Är det dyrt eller billigt att bo i Stockholm?**
Det är dyrt att bo i Stockholm men det är dyrare att bo i Paris i en lägenhet, inte med sina föräldrar.
Jag tror det är så dyrt att bo i Lyon i ett studentrum men en lägenhet är billigare. 

**•	Är det lätt eller svårt att hitta en bostad i Stockholm?**
Jag tror det är svårt att hitta en bostad i Stockholm men jag hade inte detta problem eftersom jag hade en bostad med KTH.

### Vocabulary

| | | | | | |
|-|-|-|-|-|.|
| jag söker |  je cherche | jag hittar | je trouve | 

## Framtidsplaner 1

### Questions / Answers

**Vad ska du studera?**
- Jag _studerar_ IT och datavetenskap på KTH Kista. Jag _pluggar_ till civilinjeniör i IT. Jag studerar också vetenskapfilosophi.
- Ar det intressant ?
**Vad vill du göra på fritiden?**
- Jag _brukar_ träffa vänner.
- Jag går _alltid/ofta/sällan/aldrig_ på bio.
- Jg gå på krogen _ibland_.
- Vad gör du på _fredagar/lördagar_ ?
- Brukar ni gitta på teve ?
**Planerar du att resa någonstans?** _Planning a trip somewhere?_
- Jag planera att resa i Sverige, jag vill åker i Göteborg.
- Jag resade till Riga förra veckan, det vad bra !
- Ska du åka buss eller flygplan ?
**Kommer någon och besöker dig?**
- Jag, mina foraldrar besökde mig förra månaden.
- Vi promenerade i Stockholm och gick på Modernmuseet.
- Vad gjorde ni ?


## Framtidsplaner 2 ##

### Question / Answers

**•	Var ska du arbeta?**
Jag tror att jag ska arbeta i Paris för att vara stängd från min familj men jag vill resa så jag skulle vilja arbeta i New York eller London.

**•	Planerar du att resa någonstans?**



•	Var ska du bo?
•	Kommer du att besöka Stockholm/Sverige igen?



